# STREAM_STATS_PAGE= "#{ENV['STREAM_BASE_URL']}#{ENV['STREAM_STATS']}"
# STREAM_URL= "#{ENV['STREAM_BASE_URL']}#{ENV['STREAM_FILENAME']}"
# DIRECT_STREAM_URL = "#{ENV['STREAM_BASE_URL']}#{ENV['STREAM_DIRECT_FILENAME']}"

