development:
  adapter: postgresql
  encoding: unicode
  database: hos_dev
  pool: 5
  username: myapp
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: hos_test
  pool: 5
  username: myapp
  password: password1